# Generated by Django 2.2.5 on 2019-10-16 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='street_name',
            new_name='address',
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('address', 'suburb')},
        ),
        migrations.RemoveField(
            model_name='property',
            name='house_no',
        ),
    ]
