# Generated by Django 2.2.6 on 2019-10-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20191016_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together=set(),
        ),
    ]
